### PR TITLE
Fix flask request initialization

### PR DESCRIPTION
**Pull request by andrew-gardener**
Fixes: #27

### CODE REVIEW

**Comment by ryanhiebert** [comment]
Thank you for the report and the fix. Would it work to just use `dict`, since `request.headers` should conform to the mapping protocol?
```python
headers = dict(request.headers)
```

**Comment by andrew-gardener** [comment]
Yes, your right

**Comment by ryanhiebert** [comment]
Thank you! I'm going to see what I can do about testing this a bit better before I do a release.

**Comment by ryanhiebert** [comment]
I changed my mind. I've tagged 0.8.3, and that should be on PyPI shortly.

**Pull request merged**
