### PR TITLE
Check full tagname when parsing xml

### PR DESCRIPTION
**Pull request by cutz**
Fix for #59.  When parsing xml check against the full local tag name.

### CODE REVIEW

**Comment by cutz** [comment]
In my opinion another pass at `process_xml` is warranted to reduce some of the duplication and simplify.  It looks like a good candidate for a map of tag name -> string (attribute) or callable (for more complicated parsing). Of course that would belong in its own PR.

**Comment by cutz** [comment]
I'm fine inlining that if you would prefer it be done that way. I have a personal preference to wrapping it in a function but am happy to inline based on your request.

Are you worried about the overhead of function calls there or something more stylistic?

**Comment by ryanhiebert** [comment]
No, I just prefer to avoid abstraction when reasonable, and I don't find the wrapping function giving enough value to be worth its cost. It's a bit of a taste thing. And a bit on the principle that duplication is better than the wrong abstraction. This one seems like a sub-standard abstraction, and I think we'll find a better one when we get to refactoring this code, though I can't tell you exactly what I think it will be ATM. I suspect that keeping this inline will help us see it better, though.

**Comment by ryanhiebert** [comment]
Thanks for your work on this, it's great to have people looking at this code and working on it. It's lay dormant for a while, due to my inability to provide it with much attention.

**Comment by cutz** [comment]
PR updated.

> Thanks for your work on this, it's great to have people looking at this code and working on it.

Sure thing, happy to help.

**Comment by cutz** [comment]
@ryanhiebert have you thought about when you might be able to push a new version up to pypi with these last couple of fixes?

**Pull request merged**
