### PR TITLE
Code to allow registration of an LTI 2 proxy

### PR DESCRIPTION
**Pull request by subssn21**

### CODE REVIEW

**Comment by ryanhiebert** [comment]
@subssn21 : If you accept the invitation to join the pylti organization, you should be able to merge this pull request.

**Comment by ryanhiebert** [comment]
@subssn21 : are you willing to join the organization and become a maintainer?

**Comment by subssn21** [comment]
Sure, I would be willing to help maintain this project

**Comment by ryanhiebert** [comment]
Cool. I've already approved this PR, so you can perform a squash merge at your convenience.

**Pull request merged**
